In [1]:
#%sh
#pip install sudachipy sudachidict_core

# データ取り込み

In [2]:
import pandas as pd

# kebatori_complete_df = spark.table("poc2.kebatori_complete_data").toPandas()
# kebatori_complete_df = spark.table("poc2.kebatori_complete_data_20240912_1524").toPandas()

# dfをpickleで読み込む
kebatori_df = pd.read_pickle(r"./Kebatori_DF/20241222_all_kebatori_df.pkl")
display(kebatori_df.head())
print(kebatori_df.dtypes)
display(kebatori_df.loc[:10])

,filename,title,content,tableinfo,graphinfo
Index,,,,,
0,1_08-39_1章_元.pdf,"[{'id': 5, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 3, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 46, 'file_name': '1_08-39_1章_元.pdf', '...","[{'id': 1, 'file_name': '1_08-39_1章_元.pdf', 'f..."
1,1年_中学校理科_指導書_板書例_p1.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...",[]
2,1年_中学校理科_指導書_板書例_p10.pdf,"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 4, 'file_name': '1年_中学校理科_指導書_板書例_p10....",[]
3,1年_中学校理科_指導書_板書例_p100.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p100...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p100...",[],"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p100..."
4,1年_中学校理科_指導書_板書例_p101.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p101...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p101...",[],"[{'id': 23, 'file_name': '1年_中学校理科_指導書_板書例_p10..."

filename     object
title        object
content      object
tableinfo    object
graphinfo    object
dtype: object

,filename,title,content,tableinfo,graphinfo
Index,,,,,
0,1_08-39_1章_元.pdf,"[{'id': 5, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 3, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 46, 'file_name': '1_08-39_1章_元.pdf', '...","[{'id': 1, 'file_name': '1_08-39_1章_元.pdf', 'f..."
1,1年_中学校理科_指導書_板書例_p1.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...",[]
2,1年_中学校理科_指導書_板書例_p10.pdf,"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 4, 'file_name': '1年_中学校理科_指導書_板書例_p10....",[]
3,1年_中学校理科_指導書_板書例_p100.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p100...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p100...",[],"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p100..."
4,1年_中学校理科_指導書_板書例_p101.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p101...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p101...",[],"[{'id': 23, 'file_name': '1年_中学校理科_指導書_板書例_p10..."
5,1年_中学校理科_指導書_板書例_p102.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p102...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p102...",[],"[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p102..."
6,1年_中学校理科_指導書_板書例_p103.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p103...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p103...",[],"[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p103..."
7,1年_中学校理科_指導書_板書例_p104.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p104...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p104...",[],"[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p104..."
8,1年_中学校理科_指導書_板書例_p105.pdf,[],"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p105...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p105...","[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p105..."
9,1年_中学校理科_指導書_板書例_p106.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p106...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p106...",[],"[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p106..."
10,1年_中学校理科_指導書_板書例_p107.pdf,"[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p107...","[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p107...","[{'id': 15, 'file_name': '1年_中学校理科_指導書_板書例_p10...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p107..."

In [3]:
for index, row in kebatori_df.iterrows():
    print(index, row[1])

0 ["{'id': 5, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '【文字と式】', 'region': [0.7877, 1.1632, 1.4619, 1.1632, 1.4619, 1.3109, 0.7877, 1.3109]}", "{'id': 8, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '【文字にあてはまる数2】', 'region': [3.4703, 2.6539, 4.8498, 2.6539, 4.8498, 2.809, 3.4703, 2.809]}", "{'id': 9, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '【文字にあてはまる数1」', 'region': [0.3159, 2.6561, 1.6417, 2.6561, 1.6417, 2.8094, 0.3159, 2.8094]}", "{'id': 19, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '【比】', 'region': [0.5224, 6.2644, 0.844, 6.2644, 0.844, 6.4191, 0.5224, 6.4191]}", "{'id': 22, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '【比の値', 'region': [0.5311, 8.0584, 1.0067, 8.0584, 1.0067, 8.2068, 0.5311, 8.2068]}", "{'id': 37, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 2, 'type': '章タイトル', 'figure_table_type': None, 'content': '0より小さい数は', 'region': [3.2463, 8.3735, 6.1646, 8.3735, 6.1646, 8.776, 3.2463, 8.776]}", "{'id': 40, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 2, 'type': '章タイトル', 'figure_table_type': None, 'content': '計算できるの?', 'region': [3.1907, 9.0187, 5.6779, 9.0187, 5.6779, 9.4235, 3.1907, 9.4235]}", "{'id': 43, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 3, 'type': '章タイトル', 'figure_table_type': None, 'content': '節', 'region': [1.1166, 0.9526, 1.3121, 0.9526, 1.3121, 1.1522, 1.1166, 1.1522]}", "{'id': 44, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 3, 'type': '章タイトル', 'figure_table_type': None, 'content': '「ー」のついた数ってなんだろう?', 'region': [0.6361, 1.7582, 4.4678, 1.7582, 4.4678, 2.0622, 0.6361, 2.0622]}", "{'id': 45, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 3, 'type': '章タイトル', 'figure_table_type': None, 'content': '13身のまわりから「ー」のついた数を探してみましょう。', 'region': [0.7096, 2.267, 4.9119, 2.267, 4.9119, 2.7476, 0.7096, 2.7476]}", "{'id': 54, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 5, 'type': '章タイトル', 'figure_table_type': None, 'content': '符号のついた数1', 'region': [0.802, 0.6138, 2.9413, 0.6138, 2.9413, 0.8726, 0.802, 0.8726]}", "{'id': 55, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 5, 'type': '章タイトル', 'figure_table_type': None, 'content': '0を基準とした数量', 'region': [1.1796, 1.1061, 2.7953, 1.1061, 2.7953, 1.2861, 1.1796, 1.2861]}", "{'id': 110, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 7, 'type': '章タイトル', 'figure_table_type': None, 'content': '正の数·負の数', 'region': [1.1798, 3.0845, 2.4799, 3.0845, 2.4799, 3.2676, 1.1798, 3.2676]}", "{'id': 121, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 7, 'type': '章タイトル', 'figure_table_type': None, 'content': 'どんなことがわかったかな', 'region': [1.1655, 8.6582, 2.2705, 8.6582, 2.2705, 8.7788, 1.1655, 8.7788]}", "{'id': 123, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 7, 'type': '章タイトル', 'figure_table_type': None, 'content': '次の課題へ!', 'region': [4.4352, 8.8928, 4.9839, 8.8928, 4.9839, 9.0053, 4.4352, 9.0053]}", "{'id': 126, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 8, 'type': '章タイトル', 'figure_table_type': None, 'content': '2数の大小', 'region': [0.9608, 0.6156, 2.3885, 0.6156, 2.3885, 0.872, 0.9608, 0.872]}", "{'id': 173, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 9, 'type': '章タイトル', 'figure_table_type': None, 'content': '絶対値', 'region': [1.1769, 7.1763, 1.724, 7.1763, 1.724, 7.35, 1.1769, 7.35]}", "{'id': 175, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 9, 'type': '章タイトル', 'figure_table_type': None, 'content': '見方·考え方', 'region': [5.6137, 7.799, 6.1718, 7.799, 6.1718, 7.9181, 5.6137, 7.9181]}", "{'id': 194, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 10, 'type': '章タイトル', 'figure_table_type': None, 'content': '2数の大小', 'region': [1.556, 6.272, 2.4019, 6.272, 2.4019, 6.4621, 1.556, 6.4621]}", "{'id': 202, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 10, 'type': '章タイトル', 'figure_table_type': None, 'content': 'どんなことがわかったかな', 'region': [1.3717, 8.5117, 2.4777, 8.5117, 2.4777, 8.6282, 1.3717, 8.6282]}", "{'id': 203, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 10, 'type': '章タイトル', 'figure_table_type': None, 'content': '次の課題へ!', 'region': [4.9954, 8.7449, 5.5412, 8.7449, 5.5412, 8.8572, 4.9954, 8.8572]}", "{'id': 208, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 11, 'type': '章タイトル', 'figure_table_type': None, 'content': '1数量を正の符号,負の符号を使って表すとき,', 'region': [0.6947, 1.6513, 4.0323, 1.6513, 4.0323, 1.8237, 0.6947, 1.8237]}", "{'id': 213, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 11, 'type': '章タイトル', 'figure_table_type': None, 'content': ':selected:正の数,負の数について理解している。', 'region': [0.6037, 3.5823, 2.933, 3.5823, 2.933, 3.7307, 0.6037, 3.7307]}", "{'id': 217, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 11, 'type': '章タイトル', 'figure_table_type': None, 'content': '2', 'region': [0.6818, 3.8557, 0.7647, 3.8557, 0.7647, 3.9745, 0.6818, 3.9745]}", "{'id': 225, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 11, 'type': '章タイトル', 'figure_table_type': None, 'content': ':selected:数を数直線上に表すことができる。', 'region': [0.6041, 5.7516, 2.6865, 5.7516, 2.6865, 5.9031, 0.6041, 5.9031]}", "{'id': 248, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 12, 'type': '章タイトル', 'figure_table_type': None, 'content': '節', 'region': [1.3133, 0.9522, 1.5056, 0.9522, 1.5056, 1.1508, 1.3133, 1.1508]}", "{'id': 249, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 12, 'type': '章タイトル', 'figure_table_type': None, 'content': '負の数があっても,計算できるかな?', 'region': [0.7991, 1.6405, 5.1729, 1.6405, 5.1729, 1.9406, 0.7991, 1.9406]}", "{'id': 252, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 12, 'type': '章タイトル', 'figure_table_type': None, 'content': 'ルール', 'region': [1.4116, 2.7177, 1.805, 2.7177, 1.805, 2.8529, 1.4116, 2.8529]}", "{'id': 255, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 12, 'type': '章タイトル', 'figure_table_type': None, 'content': 'コマの動かし方', 'region': [1.4125, 3.9893, 2.3252, 3.9893, 2.3252, 4.1442, 1.4125, 4.1442]}", "{'id': 267, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 13, 'type': '章タイトル', 'figure_table_type': None, 'content': '1加法', 'region': [0.7989, 0.6205, 1.6773, 0.6205, 1.6773, 0.8665, 0.7989, 0.8665]}", "{'id': 269, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 13, 'type': '章タイトル', 'figure_table_type': None, 'content': '見方·考え方', 'region': [5.784, 1.3373, 6.3408, 1.3373, 6.3408, 1.4552, 5.784, 1.4552]}", "{'id': 278, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 13, 'type': '章タイトル', 'figure_table_type': None, 'content': '目標▶正の数,負の数のたし算を考えよう。', 'region': [1.1826, 3.8563, 4.1871, 3.8563, 4.1871, 4.039, 1.1826, 4.039]}", "{'id': 288, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 14, 'type': '章タイトル', 'figure_table_type': None, 'content': '例1同符号の2数のたし算', 'region': [0.8828, 1.5835, 2.8624, 1.5835, 2.8624, 1.7524, 0.8828, 1.7524]}", "{'id': 304, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 14, 'type': '章タイトル', 'figure_table_type': None, 'content': '例2異符号の2数のたし算', 'region': [0.8846, 6.6864, 2.8615, 6.6864, 2.8615, 6.8571, 0.8846, 6.8571]}", "{'id': 320, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 15, 'type': '章タイトル', 'figure_table_type': None, 'content': '符号と絶対値に着目した加法', 'region': [1.1789, 2.491, 3.6117, 2.491, 3.6117, 2.6741, 1.1789, 2.6741]}", "{'id': 324, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 15, 'type': '章タイトル', 'figure_table_type': None, 'content': '見方·考え方', 'region': [5.4737, 3.0403, 6.0305, 3.0403, 6.0305, 3.159, 5.4737, 3.159]}", "{'id': 330, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 15, 'type': '章タイトル', 'figure_table_type': None, 'content': '正の数どうしの和と負の数どうしの和を比べてみよう。', 'region': [1.7434, 4.5851, 5.1118, 4.5851, 5.1118, 4.7529, 1.7434, 4.7529]}", "{'id': 344, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 16, 'type': '章タイトル', 'figure_table_type': None, 'content': '正の数,負の数の加法', 'region': [1.554, 1.1861, 3.3454, 1.1861, 3.3454, 1.383, 1.554, 1.383]}", "{'id': 345, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 16, 'type': '章タイトル', 'figure_table_type': None, 'content': '↑', 'region': [1.007, 1.3085, 1.0617, 1.3085, 1.0617, 1.3833, 1.007, 1.3833]}", "{'id': 380, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 17, 'type': '章タイトル', 'figure_table_type': None, 'content': '見方·考え方', 'region': [4.7057, 2.9906, 5.2607, 2.9906, 5.2607, 3.1111, 4.7057, 3.1111]}", "{'id': 428, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 18, 'type': '章タイトル', 'figure_table_type': None, 'content': '目標▶正の数,負の数のひき算を考えよう。', 'region': [1.3798, 7.397, 4.3558, 7.397, 4.3558, 7.5728, 1.3798, 7.5728]}", "{'id': 450, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 20, 'type': '章タイトル', 'figure_table_type': None, 'content': '見方·考え方', 'region': [5.2229, 1.2178, 5.7829, 1.2178, 5.7829, 1.3369, 5.2229, 1.3369]}", "{'id': 474, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 21, 'type': '章タイトル', 'figure_table_type': None, 'content': '正の数,負の数の減法', 'region': [1.3586, 1.1156, 3.1504, 1.1156, 3.1504, 1.3178, 1.3586, 1.3178]}", "{'id': 487, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 21, 'type': '章タイトル', 'figure_table_type': None, 'content': '小数や分数の減法', 'region': [1.1781, 6.0131, 2.6668, 6.0131, 2.6668, 6.1931, 1.1781, 6.1931]}", "{'id': 512, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 22, 'type': '章タイトル', 'figure_table_type': None, 'content': 'どんなことがわかったかな', 'region': [1.3741, 3.6722, 2.4769, 3.6722, 2.4769, 3.7903, 1.3741, 3.7903]}", "{'id': 518, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 22, 'type': '章タイトル', 'figure_table_type': None, 'content': 'トランプゲームで計算しよう', 'region': [1.0761, 5.348, 3.4308, 5.348, 3.4308, 5.5633, 1.0761, 5.5633]}", "{'id': 530, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 23, 'type': '章タイトル', 'figure_table_type': None, 'content': '3加法と減法の混じった計算', 'region': [0.7818, 0.6129, 4.1828, 0.6129, 4.1828, 0.8713, 0.7818, 0.8713]}", "{'id': 540, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 23, 'type': '章タイトル', 'figure_table_type': None, 'content': '目標▶加法と減法の混じった計算を考えよう。', 'region': [1.1826, 3.7673, 4.3333, 3.7673, 4.3333, 3.949, 1.1826, 3.949]}", "{'id': 576, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 25, 'type': '章タイトル', 'figure_table_type': None, 'content': '問6次の計算をしなさい。', 'region': [0.6822, 1.779, 2.5681, 1.779, 2.5681, 1.9454, 0.6822, 1.9454]}", "{'id': 587, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 25, 'type': '章タイトル', 'figure_table_type': None, 'content': 'どんなことがわかったかな', 'region': [1.1668, 3.526, 2.2698, 3.526, 2.2698, 3.6514, 1.1668, 3.6514]}", "{'id': 589, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 25, 'type': '章タイトル', 'figure_table_type': None, 'content': '次の課題へ!', 'region': [4.7287, 3.7625, 5.2773, 3.7625, 5.2773, 3.8781, 4.7287, 3.8781]}", "{'id': 594, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 25, 'type': '章タイトル', 'figure_table_type': None, 'content': '「6-8」の計算と意味', 'region': [0.8774, 5.4124, 2.7149, 5.4124, 2.7149, 5.6368, 0.8774, 5.6368]}", "{'id': 624, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 26, 'type': '章タイトル', 'figure_table_type': None, 'content': '減法でも交換法則·結合法則は成り立つの?', 'region': [1.0536, 5.8611, 4.522, 5.8611, 4.522, 6.0721, 1.0536, 6.0721]}", "{'id': 639, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 27, 'type': '章タイトル', 'figure_table_type': None, 'content': '1', 'region': [0.8162, 1.5342, 0.888, 1.5342, 0.888, 1.7127, 0.8162, 1.7127]}", "{'id': 640, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 27, 'type': '章タイトル', 'figure_table_type': None, 'content': '3', 'region': [0.7965, 5.7157, 0.9088, 5.7157, 0.9088, 5.8924, 0.7965, 5.8924]}", "{'id': 658, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 28, 'type': '章タイトル', 'figure_table_type': None, 'content': '次の課題へ!', 'region': [4.946, 8.5319, 5.4977, 8.5319, 5.4977, 8.6471, 4.946, 8.6471]}", "{'id': 664, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 29, 'type': '章タイトル', 'figure_table_type': None, 'content': '1乗法', 'region': [0.8006, 0.6251, 1.6765, 0.6251, 1.6765, 0.8662, 0.8006, 0.8662]}", "{'id': 703, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 31, 'type': '章タイトル', 'figure_table_type': None, 'content': '見方·考え方', 'region': [5.4975, 1.963, 6.0541, 1.963, 6.0541, 2.0835, 5.4975, 2.0835]}", "{'id': 708, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 31, 'type': '章タイトル', 'figure_table_type': None, 'content': '例1同符号の2数の積', 'region': [0.6866, 3.0851, 2.3616, 3.0851, 2.3616, 3.2549, 0.6866, 3.2549]}", "{'id': 714, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 31, 'type': '章タイトル', 'figure_table_type': None, 'content': '例2異符号の2数の積', 'region': [0.6866, 4.7081, 2.3715, 4.7081, 2.3715, 4.8791, 0.6866, 4.8791]}", "{'id': 726, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 31, 'type': '章タイトル', 'figure_table_type': None, 'content': '正の数,負の数の乗法', 'region': [1.36, 7.9488, 3.1489, 7.9488, 3.1489, 8.1414, 1.36, 8.1414]}", "{'id': 727, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 31, 'type': '章タイトル', 'figure_table_type': None, 'content': '↑', 'region': [0.8103, 8.0717, 0.8632, 8.0717, 0.8632, 8.1433, 0.8103, 8.1433]}", "{'id': 743, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 32, 'type': '章タイトル', 'figure_table_type': None, 'content': '乗法の交換法則·結合法則', 'region': [1.3764, 5.9136, 3.61, 5.9136, 3.61, 6.0966, 1.3764, 6.0966]}", "{'id': 753, 'file_name': '1_08-39_1章_元.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpmscsuezn.pdf', 'page_number': 32, 'type': '章タイトル', 'figure_table_type': None, 'content': '見方·考え方', 'region': [5.2791, 8.656, 5.8339, 8.656, 5.8339, 8.7695, 5.2791, 8.7695]}"]
1 ["{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p1.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmp_3dbj4om.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '◆オンライン資料についてく', 'region': [0.5833, 0.7527, 2.2993, 0.7527, 2.2993, 0.9152, 0.5833, 0.9152]}"]
2 ["{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p10.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmpuz4u1o26.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '1-1動植物の分類単元の指導展開と評価規準例', 'region': [0.5854, 1.2866, 3.7466, 1.2866, 3.7466, 1.4527, 0.5854, 1.4527]}"]
3 ["{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p100.pdf', 'file_path': 'C:\\\\Users\\\\banqu\\\\AppData\\\\Local\\\\Temp\\\\tmp1pbepd7w.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '第3章2|カのつり合い【探究8】(第14時/17時間)p.139~140', 'region': [0.604, 0.8639, 6.6281, 0.8639, 6.6281, 1.0427, 0.604, 1.0427]}"]

C:\Users\banqu\AppData\Local\Temp\ipykernel_42964\933956903.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(index, row[1])

In [4]:
def convert_dictlist_to_stringlist(dict_list):
    string_list = []
    for d in dict_list:
        string_list.append(f"{str(d)}")
    return string_list

### title 列のファイル名から .pdf　を削除 ⇒　実施する必要ないと思うのでパス

In [4]:
# def remove_pdf_suffix(title):
    # if isinstance(title, str) and title[0].endswith('.pdf'):
        # return title[:-4]
    # return title

# Sudachiシノニム処理

In [5]:
# Sudachiの動作確認
from sudachipy import Dictionary, SplitMode
from sudachipy.morpheme import Morpheme
from sudachipy.tokenizer import Tokenizer
# Sudachiの辞書を初期化
dictionary = Dictionary(dict="core")
# トークナイザーを作成
tokenizer = dictionary.create(SplitMode.C)
# トークナイザーを初期化
morphemes = tokenizer.tokenize('')

# トークナイズ処理
text = "これはテストです。"
tokens = tokenizer.tokenize(text, out=morphemes)
for token in tokens:
    print(f"表層形式：{token.surface()}","\n", f"正規化後の表現：{token.normalized_form()}","\n")

表層形式：これ
 正規化後の表現：此れ

表層形式：は
 正規化後の表現：は

表層形式：テスト
 正規化後の表現：テスト

表層形式：です
 正規化後の表現：です

表層形式：。
 正規化後の表現：。

In [6]:
# 動作確認
import pandas as pd

# サンプルデータフレームの作成
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
df = pd.DataFrame(data)
display(df)

# df.iterrows() を使用して各行を反復処理
for index, row in df.iterrows():
    print(f"Index: {index}")
    print(f"Row data:\n{row}")
    print(getattr(row, 'A'),"\n")

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

Index: 0
Row data:
A    1
B    4
C    7
Name: 0, dtype: int64
1

Index: 1
Row data:
A    2
B    5
C    8
Name: 1, dtype: int64
2

Index: 2
Row data:
A    3
B    6
C    9
Name: 2, dtype: int64
3

In [7]:
# 動作確認
import ast

# 文字列として表現された辞書
dict_str = '{"key": "value"}'
print(dict_str)  # 出力: {'key': 'value'}
print(type(dict_str))  # 出力: <class 'str'>

# 文字列を辞書に変換
dict_obj = ast.literal_eval(dict_str)
print(dict_obj)  # 出力: {'key': 'value'}
print(type(dict_obj))  # 出力: <class 'dict'>

{"key": "value"}
<class 'str'>
{'key': 'value'}
<class 'dict'>

In [9]:
from sudachipy import Dictionary, SplitMode, Tokenizer
from sudachipy.morpheme import Morpheme
from typing import Literal
import ast

class SudachiNounNormalizer:
    """google style docstring
    A class to normalize Japanese nouns using SudachiPy."""
    SPLIT_MODES = {
        "A": SplitMode.A,
        "B": SplitMode.B,
        "C": SplitMode.C
    }
    MAX_LENGTH = 18000

    def __init__(
            self,
            dict_type: Literal["small", "core", "full"] = "core",
            split_mode: Literal["A", "B", "C"] = "C")-> None:
        """google style docstring
        Args:
            dict_type (Literal["small", "core", "full"], optional): The type of dictionary to use. Defaults to "core".
            split_mode (Literal["A", "B", "C"], optional): The split mode to use. Defaults to "C".
        """
        self._dictionary = Dictionary(dict=dict_type)
        self._tokenizer = self._dictionary.create(self.SPLIT_MODES[split_mode])
        self._morphemes = self.tokenizer.tokenize('')
        self.is_noun = self._dictionary.pos_matcher([("名詞",)])

    @property
    def dictionary(self) -> Dictionary:
        """google style docstring
        Returns:
            Dictionary: The dictionary object."""
        return self._dictionary

    @property
    def tokenizer(self) -> Tokenizer:
        """google style docstring
        Returns:
            Tokenizer: The tokenizer object."""
        return self._tokenizer
    # 名詞のみを正規化する
    def morpheme2norm(self, morpheme: Morpheme) -> str:
        return morpheme.normalized_form() if self.is_noun(morpheme) else morpheme.surface()

    def normalize(self, document: str) -> str:
        """google style docstring
        Normalizes a document.
        Args:
            document (str): The document to normalize.
        Returns:
            str: The normalized document."""
        if not isinstance(document, str):
            raise ValueError("Input must be a string.")
        sub_documents = (document[i:i+self.MAX_LENGTH] for i in range(0, len(document), self.MAX_LENGTH))
        return "".join(
            (
                "".join((
                    self.morpheme2norm(morpheme)
                    for morpheme in self.tokenizer.tokenize(sub_document, out=self._morphemes)
                ))
                for sub_document in sub_documents
            )
        )

    def extract_corrected_words(self, document: str) -> list:
        """google style docstring
        Extracts corrected words from a document.
        Args:
            document (str): The document to extract corrected words from.
        Returns:
            list: A list of tuples containing the original word and the corrected word."""
        if not isinstance(document, str):
            raise ValueError("Input must be a string.")
        sub_documents = (document[i:i+self.MAX_LENGTH] for i in range(0, len(document), self.MAX_LENGTH))
        corrected_words = []
        for sub_document in sub_documents:
            for morpheme in self.tokenizer.tokenize(sub_document, out=self._morphemes):
                normalized_form = self.morpheme2norm(morpheme)
                if self.is_noun(morpheme) and normalized_form != morpheme.surface():
                    corrected_words.append((morpheme.surface(), normalized_form))
        return corrected_words

def apply_normalizing_function(df, normalizer)-> tuple:
    """google style docstring
    Args:
        df (pd.DataFrame): The DataFrame to normalize.
        normalizer (SudachiNounNormalizer): The normalizer object to use.
    Returns:
        tuple: A tuple containing the normalized DataFrame, a list of words to normalize, and a DataFrame of words to normalize."""
    # First check which words need to be normalized
    words_to_normalize = []
    for index, row in df.iterrows():
        # majorcategory = getattr(row, 'majorcategory') パス
        title = getattr(row, 'title')
        for column in df.columns:
            # if column == 'content' or column == 'tableinfo' or column == 'graphinfo':
            if column == 'content' or column == 'tableinfo' or column == 'graphinfo' or column == 'title':
                # Retrieve list of dicts
                cell_val = row[column]
                list_of_dicts = [ast.literal_eval(item) for item in cell_val]

                for dict in list_of_dicts:
                    # Check if 'file_name' key exists in the dictionary
                    if 'file_name' in dict:
                        # Check which words need to be normalized
                        extracted_corrected_words = normalizer.extract_corrected_words(dict['content'])
                        if extracted_corrected_words:
                            # words_to_normalize.append({dict['file_name'] : extracted_corrected_words, 'id' : dict['id']})
                            # words_to_normalize.append({'title': title, 'id': dict['id'], 'corrected_words': extracted_corrected_words})
                            string_extracted = str(extracted_corrected_words)
                            #words_to_normalize.append({'filename' : dict['file_name'], 'majorcategory' : majorcategory,  'corrected_words': string_extracted})
                            words_to_normalize.append({'filename' : dict['file_name'],  'corrected_words': string_extracted})
                        # Normalize words
                        dict['content'] = normalizer.normalize(dict['content'])
                converted_back = convert_dictlist_to_stringlist(list_of_dicts)
                df.at[index, column] = converted_back

    words_to_normalize_df = pd.DataFrame(words_to_normalize)
    return (df, words_to_normalize, words_to_normalize_df)


normalizer = SudachiNounNormalizer(dict_type="core", split_mode="C")
normalized_result = apply_normalizing_function(kebatori_df, normalizer)
sudachi_df = normalized_result[0]
words_to_normalize = normalized_result[1]
words_to_normalize_df = normalized_result[2]
display(sudachi_df.head())

,filename,title,content,tableinfo,graphinfo
Index,,,,,
0,1_08-39_1章_元.pdf,"[{'id': 5, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 3, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 46, 'file_name': '1_08-39_1章_元.pdf', '...","[{'id': 1, 'file_name': '1_08-39_1章_元.pdf', 'f..."
1,1年_中学校理科_指導書_板書例_p1.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...",[]
2,1年_中学校理科_指導書_板書例_p10.pdf,"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 4, 'file_name': '1年_中学校理科_指導書_板書例_p10....",[]
3,1年_中学校理科_指導書_板書例_p100.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p100...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p100...",[],"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p100..."
4,1年_中学校理科_指導書_板書例_p101.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p101...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p101...",[],"[{'id': 23, 'file_name': '1年_中学校理科_指導書_板書例_p10..."

In [11]:
# dfをpickleで保存しておく
# sudachi_df.to_pickle(r"./Sudachi_DF/20241222_all_sudachi_df.pkl")
# dfをpickleで読み込む
sudachi_df = pd.read_pickle(r"./Sudachi_DF/20241222_all_sudachi_df.pkl")
display(sudachi_df.head())

,filename,title,content,tableinfo,graphinfo
Index,,,,,
0,1_08-39_1章_元.pdf,"[{'id': 5, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 3, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 46, 'file_name': '1_08-39_1章_元.pdf', '...","[{'id': 1, 'file_name': '1_08-39_1章_元.pdf', 'f..."
1,1年_中学校理科_指導書_板書例_p1.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...",[]
2,1年_中学校理科_指導書_板書例_p10.pdf,"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 4, 'file_name': '1年_中学校理科_指導書_板書例_p10....",[]
3,1年_中学校理科_指導書_板書例_p100.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p100...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p100...",[],"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p100..."
4,1年_中学校理科_指導書_板書例_p101.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p101...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p101...",[],"[{'id': 23, 'file_name': '1年_中学校理科_指導書_板書例_p10..."

In [12]:
# 動作テスト
# SudachiNounNormalizer クラスのインスタンスを作成
normalizer = SudachiNounNormalizer(dict_type="core", split_mode="C")

# 正規化対象のテキスト
text = "これはFe（鉄）です。"

# 正規化された単語を抽出
corrected_words = normalizer.extract_corrected_words(text)
print(corrected_words)  # 出力: [('テスト', 'テスト')]

[('Fe', 'FE')]

In [13]:
print(words_to_normalize)

[{'filename': '1_08-39_1章_元.pdf', 'corrected_words': "[('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒')]"}, {'filename': '1_08-39_1章_元.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1_08-39_1章_元.pdf', 'corrected_words': "[('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒')]"}, {'filename': '1_08-39_1章_元.pdf', 'corrected_words': "[('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒')]"}, {'filename': '1年_中学校理科_指導書_板書例_p100.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p107.pdf', 'corrected_words': "[('か所', '箇所')]"}, {'filename': '1年_中学校理科_指導書_板書例_p108.pdf', 'corrected_words': "[('かんらん', '橄欖')]"}, {'filename': '1年_中学校理科_指導書_板書例_p109.pdf', 'corrected_words': "[('かんらん', '橄欖')]"}, {'filename': '1年_中学校理科_指導書_板書例_p110.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p115.pdf', 'corrected_words': "[('礫', '飛礫')]"}, {'filename': '1年_中学校理科_指導書_板書例_p115.pdf', 'corrected_words': "[('礫', '飛礫')]"}, {'filename': '1年_中学校理科_指導書_板書例_p118.pdf', 'corrected_words': "[('売', '売り'), ('く', '九')]"}, {'filename': '1年_中学校理科_指導書_板書例_p119.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p120.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p121.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p122.pdf', 'corrected_words': "[('止', '止め')]"}, {'filename': '1年_中学校理科_指導書_板書例_p126.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p132.pdf', 'corrected_words': "[('8万', '80000'), ('三', '3'), ('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p133.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p133.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p14.pdf', 'corrected_words': "[('二', '2'), ('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p25.pdf', 'corrected_words': "[('巻きばね', '巻き発条')]"}, {'filename': '1年_中学校理科_指導書_板書例_p32.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p33.pdf', 'corrected_words': "[('ろいろ', '蝋色')]"}, {'filename': '1年_中学校理科_指導書_板書例_p35.pdf', 'corrected_words': "[('一', '1'), ('九', '9'), ('三', '3')]"}, {'filename': '1年_中学校理科_指導書_板書例_p37.pdf', 'corrected_words': "[('九', '9'), ('一九', '19')]"}, {'filename': '1年_中学校理科_指導書_板書例_p39.pdf', 'corrected_words': "[('こや', '小屋')]"}, {'filename': '1年_中学校理科_指導書_板書例_p39.pdf', 'corrected_words': "[('こや', '小屋')]"}, {'filename': '1年_中学校理科_指導書_板書例_p40.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p44.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p46.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p53.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p57.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p60.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p65.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p66.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p75.pdf', 'corrected_words': "[('一', '1'), ('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p76.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p76.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p77.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p77.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p77.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p81.pdf', 'corrected_words': "[('四', '4')]"}, {'filename': '1年_中学校理科_指導書_板書例_p85.pdf', 'corrected_words': "[('む', '六')]"}, {'filename': '1年_中学校理科_指導書_板書例_p91.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p91.pdf', 'corrected_words': "[('m/s2', 'メートル毎秒毎秒')]"}, {'filename': '1年_中学校理科_指導書_板書例_p91.pdf', 'corrected_words': "[('四', '4')]"}, {'filename': '1年_中学校理科_指導書_板書例_p92.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '1年_中学校理科_指導書_板書例_p97.pdf', 'corrected_words': "[('巻きばね', '巻き発条')]"}, {'filename': '1年_中学校理科_指導書_板書例_p97.pdf', 'corrected_words': "[('巻きばね', '巻き発条')]"}, {'filename': '1年_中学校理科_指導書_板書例_p97.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '1年_中学校理科_指導書_板書例_p98.pdf', 'corrected_words': "[('巻きばね', '巻き発条')]"}, {'filename': '1年_中学校理科_指導書_板書例_p98.pdf', 'corrected_words': "[('巻きばね', '巻き発条')]"}, {'filename': '2年_中学校理科_指導書_板書例_p104.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p104.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p107.pdf', 'corrected_words': "[('ま下', '真下')]"}, {'filename': '2年_中学校理科_指導書_板書例_p113.pdf', 'corrected_words': "[('また下', '股下')]"}, {'filename': '2年_中学校理科_指導書_板書例_p122.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p128.pdf', 'corrected_words': "[('粥', 'ジョウ')]"}, {'filename': '2年_中学校理科_指導書_板書例_p129.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p134.pdf', 'corrected_words': "[('九', '9'), ('引', '引き')]"}, {'filename': '2年_中学校理科_指導書_板書例_p138.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p140.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p141.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p146.pdf', 'corrected_words': "[('九', '9'), ('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p149.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p150.pdf', 'corrected_words': "[('まま', '侭')]"}, {'filename': '2年_中学校理科_指導書_板書例_p153.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p154.pdf', 'corrected_words': "[('四', '4')]"}, {'filename': '2年_中学校理科_指導書_板書例_p27.pdf', 'corrected_words': "[('巻きばね', '巻き発条')]"}, {'filename': '2年_中学校理科_指導書_板書例_p42.pdf', 'corrected_words': "[('お願い', '御願い')]"}, {'filename': '2年_中学校理科_指導書_板書例_p48.pdf', 'corrected_words': "[('和物', '和え物')]"}, {'filename': '2年_中学校理科_指導書_板書例_p48.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p48.pdf', 'corrected_words': "[('四', '4'), ('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p49.pdf', 'corrected_words': "[('二', '2')]"}, {'filename': '2年_中学校理科_指導書_板書例_p50.pdf', 'corrected_words': "[('十九', '19'), ('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p50.pdf', 'corrected_words': "[('九', '9'), ('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p51.pdf', 'corrected_words': "[('九', '9'), ('九', '9'), ('く', '九')]"}, {'filename': '2年_中学校理科_指導書_板書例_p53.pdf', 'corrected_words': "[('51九', '519')]"}, {'filename': '2年_中学校理科_指導書_板書例_p53.pdf', 'corrected_words': "[('九', '9'), ('かに', '蟹'), ('く', '九'), ('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p55.pdf', 'corrected_words': "[('三1', '31')]"}, {'filename': '2年_中学校理科_指導書_板書例_p55.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p56.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p58.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p60.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p60.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p60.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p61.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p64.pdf', 'corrected_words': "[('物書', '物書き')]"}, {'filename': '2年_中学校理科_指導書_板書例_p65.pdf', 'corrected_words': "[('お節', '御節')]"}, {'filename': '2年_中学校理科_指導書_板書例_p67.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '2年_中学校理科_指導書_板書例_p68.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p69.pdf', 'corrected_words': "[('九', '9'), ('きず', '傷'), ('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p80.pdf', 'corrected_words': "[('九', '9'), ('まと', '的')]"}, {'filename': '2年_中学校理科_指導書_板書例_p81.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p83.pdf', 'corrected_words': "[('引', '引き')]"}, {'filename': '2年_中学校理科_指導書_板書例_p83.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '2年_中学校理科_指導書_板書例_p86.pdf', 'corrected_words': "[('0.08九', '0.089')]"}, {'filename': '2年_中学校理科_指導書_板書例_p91.pdf', 'corrected_words': "[('四248', '4248')]"}, {'filename': '3年_中学校理科_指導書_板書例_p102.pdf', 'corrected_words': "[('ど力', '努力'), ('この頃', '此の頃')]"}, {'filename': '3年_中学校理科_指導書_板書例_p108.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p109.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p112.pdf', 'corrected_words': "[('九42', '942')]"}, {'filename': '3年_中学校理科_指導書_板書例_p120.pdf', 'corrected_words': "[('地球(アース)', '地球')]"}, {'filename': '3年_中学校理科_指導書_板書例_p120.pdf', 'corrected_words': "[('四', '4')]"}, {'filename': '3年_中学校理科_指導書_板書例_p122.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p123.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p124.pdf', 'corrected_words': "[('ほし空', '星空')]"}, {'filename': '3年_中学校理科_指導書_板書例_p124.pdf', 'corrected_words': "[('シット', '嫉妬')]"}, {'filename': '3年_中学校理科_指導書_板書例_p126.pdf', 'corrected_words': "[('一', '1'), ('一', '1'), ('四', '4')]"}, {'filename': '3年_中学校理科_指導書_板書例_p129.pdf', 'corrected_words': "[('BCd', 'bcd')]"}, {'filename': '3年_中学校理科_指導書_板書例_p130.pdf', 'corrected_words': "[('九', '9'), ('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p131.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p131.pdf', 'corrected_words': "[('国国', '国々')]"}, {'filename': '3年_中学校理科_指導書_板書例_p136.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p136.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p136.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p136.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p142.pdf', 'corrected_words': "[('はち', '八')]"}, {'filename': '3年_中学校理科_指導書_板書例_p142.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p144.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p145.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p147.pdf', 'corrected_words': "[('一', '1'), ('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p151.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p23.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p29.pdf', 'corrected_words': "[('巻きばね', '巻き発条')]"}, {'filename': '3年_中学校理科_指導書_板書例_p37.pdf', 'corrected_words': "[('ほく', '北'), ('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p39.pdf', 'corrected_words': "[('九', '9'), ('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p44.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p45.pdf', 'corrected_words': "[('九', '9'), ('m/s2', 'メートル毎秒毎秒')]"}, {'filename': '3年_中学校理科_指導書_板書例_p45.pdf', 'corrected_words': "[('m/s2', 'メートル毎秒毎秒'), ('m/s2', 'メートル毎秒毎秒')]"}, {'filename': '3年_中学校理科_指導書_板書例_p46.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p52.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p54.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p54.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p57.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p68.pdf', 'corrected_words': "[('三', '3')]"}, {'filename': '3年_中学校理科_指導書_板書例_p70.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p70.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p73.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p73.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p74.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p75.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p76.pdf', 'corrected_words': "[('粥', 'ジョウ')]"}, {'filename': '3年_中学校理科_指導書_板書例_p77.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p78.pdf', 'corrected_words': "[('組み', '組')]"}, {'filename': '3年_中学校理科_指導書_板書例_p81.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p81.pdf', 'corrected_words': "[('日よう', '日曜')]"}, {'filename': '3年_中学校理科_指導書_板書例_p82.pdf', 'corrected_words': "[('もろ', '諸'), ('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p84.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p84.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p90.pdf', 'corrected_words': "[('九', '9'), ('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p96.pdf', 'corrected_words': "[('一', '1')]"}, {'filename': '3年_中学校理科_指導書_板書例_p96.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p97.pdf', 'corrected_words': "[('九', '9')]"}, {'filename': '3年_中学校理科_指導書_板書例_p98.pdf', 'corrected_words': "[('為手', '仕手')]"}]

In [14]:
# from datetime import datetime, timedelta

# # 現在のUTC日時を取得
# now_utc = datetime.utcnow()

# # 日本時間 (UTC+9) に変換
# now_japan = now_utc + timedelta(hours=9)

# # yyyyMMddHHmm形式の文字列に変換
# formatted_date_japan = now_japan.strftime('%Y%m%d_%H%M')

# display(formatted_date_japan)

# # Convert Pandas DataFrame to Spark DataFrame
# words_to_normalize_spark_df = spark.createDataFrame(words_to_normalize_df)
# # print("xxxx")
# # Write the Spark DataFrame to CSV
# words_to_normalize_spark_df.coalesce(1).write.option("header", "true").csv(
#     f"/mnt/rag-poc-q2-container/normalizing_result_small_{formatted_date_japan}",
#     mode="overwrite"
# )
# # print("yyy")

# # Display the Spark DataFrame
# display(words_to_normalize_spark_df)

In [15]:
# # Convert Pandas DataFrame to Spark DataFrame
# words_to_normalize_spark_df = spark.createDataFrame(words_to_normalize)
# # print("xxxx")
# # Write the Spark DataFrame to CSV
# words_to_normalize_spark_df.coalesce(1).write.option("header", "true").csv(
#     f"/mnt/rag-poc-q2-container/normalizing_result_{formatted_date_japan}",
#     mode="overwrite"
# )
# # print("yyy")

# # Display the Spark DataFrame
# display(words_to_normalize_spark_df)

### データベースに保存 ⇒　ローカルで実施する場合はパス

In [16]:
# from datetime import datetime, timedelta

# def save_df_to_catalog(df, table_name: str):
#     # 現在のUTC日時を取得
#     now_utc = datetime.utcnow()
#     # 日本時間 (UTC+9) に変換
#     now_japan = now_utc + timedelta(hours=9)
#     # yyyyMMddHHmm形式の文字列に変換
#     formatted_date_japan = now_japan.strftime('%Y%m%d_%H%M')

#     df = spark.createDataFrame(df)
#     # # Convert Pandas DataFrame to Spark DataFrame if necessary
#     # if isinstance(df, pd.DataFrame):
#     #     df = spark.createDataFrame(df)

#     # Create the schema in the specified catalog and schema
#     spark.sql("CREATE SCHEMA IF NOT EXISTS hive_metastore.poc2")

#     # Save the DataFrame as a table in the specified schema
#     df.write.mode("overwrite").saveAsTable(f"poc2.{table_name}_{formatted_date_japan}")
    
#     print(f"Table 'poc2.{table_name}_{formatted_date_japan}' was created.")
#     check_df = spark.table(f"poc2.{table_name}_{formatted_date_japan}")
#     display(check_df)

# save_df_to_catalog(sudachi_df, "sudachi_complete_data")

In [17]:
# sample_df = spark.table(f"poc2.sudachi_complete_data_20240912_1958").toPandas()
# display(sample_df.loc[880:920])